// Registers every built-in step component, which is what makes "@flowkit-io/react"
// work with no further imports. Each line is the very module published as
// "@flowkit-io/react/steps/<type>", so the batteries-included entry and the opt-in
// ones share a single registration site instead of two that can drift apart.
import "./entries/intro"
import "./entries/select-cards"
import "./entries/scale"
import "./entries/chips"
import "./entries/faces"
import "./entries/notes"
import "./entries/media"
import "./entries/file"
import "./entries/media-display"
import "./entries/date-time"
import "./entries/nps"
import "./entries/multi-select"
import "./entries/radio"
import "./entries/text"
import "./entries/review"
import "./entries/confirmation"
import "./entries/oauth"
import "./entries/group"
import "./entries/signature"
