import { parseFlow, type Flow } from "@flowkit/core"

/** Preset for collecting reports of unpleasant smells in an area. */
export const odoriFlow: Flow = parseFlow({
  id: "odori",
  title: "Segnala un odore",
  steps: [
    {
      id: "intro",
      type: "intro",
      title: "Che aria tira?",
      subtitle:
        "Senti un cattivo odore nel tuo quartiere? Segnalalo in 30 secondi e aiuta a mappare la qualità dell'aria.",
      emoji: "👃",
      cta: "Segnala un odore →",
      livePill: "34 segnalazioni oggi in zona",
    },
    {
      id: "location",
      type: "location",
      title: "Dove lo senti?",
      subtitle: "Abbiamo rilevato la tua posizione. Trascina il segnaposto per correggerla.",
      icon: "📍",
      showMap: true,
      detectedLabel: "Via Roma, 24",
      detectedSubLabel: "Battipaglia (SA) · ±15 m",
      manualEntryLabel: "Inserisci un indirizzo manualmente",
    },
    {
      id: "smell-type",
      type: "select-cards",
      title: "Che tipo di odore?",
      subtitle: "Scegli la categoria che si avvicina di più.",
      icon: "🏷️",
      multiple: false,
      options: [
        { value: "sewage", label: "Fognario", emoji: "🥚", description: "Uova marce, zolfo" },
        { value: "chemical", label: "Chimico", emoji: "🧪", description: "Solventi, vernici" },
        { value: "smoke", label: "Bruciato", emoji: "🔥", description: "Fumo, combustione" },
        { value: "waste", label: "Rifiuti", emoji: "🗑️", description: "Organico, marcio" },
        { value: "farm", label: "Agricolo", emoji: "🚜", description: "Letame, stalla" },
        { value: "industrial", label: "Industriale", emoji: "🏭", description: "Fabbrica, gas" },
      ],
    },
    {
      id: "intensity",
      type: "scale",
      title: "Quanto è forte?",
      subtitle: "Valuta l'intensità dell'odore che percepisci.",
      icon: "📊",
      variant: "slider",
      min: 0,
      max: 6,
      minLabel: "0 · Assente",
      maxLabel: "6 · Estremo",
      valueLabels: ["Assente", "Molto debole", "Debole", "Distinto", "Forte", "Molto forte", "Estremo"],
      valueColors: [
        "#7D7A75",
        "#46A171",
        "#46A171",
        "#D5803B",
        "#D5803B",
        "#E56458",
        "#E56458",
      ],
    },
    {
      id: "duration",
      type: "chips",
      title: "Da quanto lo senti?",
      icon: "⏱️",
      multiple: false,
      options: [
        { value: "lt5", label: "< 5 min" },
        { value: "5-30", label: "5–30 min" },
        { value: "gt30", label: "> 30 min" },
        { value: "persistent", label: "Persistente" },
      ],
    },
    {
      id: "hedonic",
      type: "faces",
      title: "Quanto è fastidioso?",
      required: false,
      icon: "🙂",
      faces: [
        { value: "1", emoji: "😊" },
        { value: "2", emoji: "😐" },
        { value: "3", emoji: "😕" },
        { value: "4", emoji: "🤢" },
        { value: "5", emoji: "🤮" },
      ],
    },
    {
      id: "notes-photo-group",
      type: "group",
      title: "Vuoi aggiungere altro?",
      subtitle: "Facoltativo. Ogni dettaglio aiuta l'analisi.",
      icon: "📝",
      required: false,
      layout: "stack",
      steps: [
        {
          id: "notes",
          type: "notes",
          required: false,
          placeholder: "Es. l'odore aumenta quando tira vento da nord…",
        },
        {
          id: "photo",
          type: "photo",
          required: false,
          placeholder: "Aggiungi una foto",
        },
      ],
    },
    {
      id: "review",
      type: "review",
      title: "Tutto pronto?",
      subtitle: "Controlla e invia la tua segnalazione.",
      meta: "🌬️ Aggiungeremo automaticamente meteo e direzione del vento",
    },
    {
      id: "confirmation",
      type: "confirmation",
      title: "Grazie!",
      message: "La tua segnalazione è stata registrata e contribuisce alla mappa della tua zona.",
      stats: [
        { value: "35", label: "segnalazioni oggi in zona" },
        { value: "#12", label: "la tua di oggi" },
      ],
      primaryCta: "Torna alla home",
      secondaryCta: "Nuova segnalazione",
      emailShare: {
        enabled: true,
        subject: "La mia segnalazione odore",
        buttonLabel: "Invia via email",
        helpText: "Vuoi salvare una copia della tua segnalazione? Ricevila via email.",
      },
    },
  ],
})
