import { parseFlow, type Flow } from "@flowkit-io/core"

/** Preset for booking a restaurant table. */
export const restaurantFlow: Flow = parseFlow({
  id: "restaurant",
  title: "Prenota un tavolo",
  steps: [
    {
      id: "intro",
      type: "intro",
      key: "prenota_un_tavolo",
      title: "Prenota un tavolo",
      subtitle: "Scegli sede, data e numero di ospiti in meno di un minuto.",
      image: { kind: "emoji", value: "🍽️" },
      cta: "Prenota un tavolo →",
    },
    {
      id: "branch",
      type: "select-cards",
      key: "quale_sede",
      title: "Quale sede?",
      subtitle: "Scegli il ristorante più comodo per te.",
      image: { kind: "emoji", value: "📍" },
      multiple: false,
      options: [
        { value: "centro", label: "Centro", emoji: "🏙️", description: "Via Roma, 12" },
        { value: "lungomare", label: "Lungomare", emoji: "🌊", description: "Via del Porto, 4" },
        { value: "collina", label: "Collina", emoji: "🌳", description: "Via dei Colli, 88" },
      ],
    },
    {
      id: "party-size",
      type: "text",
      key: "in_quanti_sarete",
      title: "In quanti sarete?",
      subtitle: "Numero totale di ospiti, bambini inclusi.",
      image: { kind: "emoji", value: "🧑‍🤝‍🧑" },
      variant: "number",
      placeholder: "Es. 4",
    },
    {
      id: "date-time",
      type: "date-time",
      key: "quando",
      title: "Quando?",
      subtitle: "Scegli data e ora del tavolo.",
      image: { kind: "emoji", value: "🗓️" },
      mode: "datetime",
      disablePast: true,
    },
    {
      id: "seating",
      type: "chips",
      key: "dove_preferisci_sederti",
      title: "Dove preferisci sederti?",
      subtitle: "Ti riserviamo il posto in base alla disponibilità.",
      image: { kind: "emoji", value: "🪑" },
      multiple: false,
      options: [
        { value: "indoor", label: "Interno" },
        { value: "outdoor", label: "Esterno" },
        { value: "bar", label: "Bancone" },
      ],
    },
    {
      id: "occasion",
      type: "select-cards",
      key: "un_occasione_speciale",
      title: "Un'occasione speciale?",
      subtitle: "Facoltativo: ci aiuta a preparare un dettaglio in più.",
      image: { kind: "emoji", value: "🎉" },
      required: false,
      multiple: false,
      options: [
        { value: "birthday", label: "Compleanno", emoji: "🎂" },
        { value: "anniversary", label: "Anniversario", emoji: "💐" },
        { value: "business", label: "Cena di lavoro", emoji: "💼" },
      ],
    },
    {
      id: "dietary-notes",
      type: "notes",
      key: "allergie_o_richieste_particolari",
      title: "Allergie o richieste particolari?",
      subtitle: "Facoltativo.",
      image: { kind: "emoji", value: "📝" },
      required: false,
      placeholder: "Es. intolleranza al glutine, seggiolone per bambini…",
    },
    {
      id: "contact-name",
      type: "text",
      key: "a_che_nome",
      title: "A che nome?",
      subtitle: "Il nome a cui intestare la prenotazione.",
      image: { kind: "emoji", value: "🧾" },
      placeholder: "Nome e cognome",
    },
    {
      id: "contact-email",
      type: "text",
      key: "la_tua_email",
      title: "La tua email",
      subtitle: "Ti invieremo la conferma della prenotazione.",
      image: { kind: "emoji", value: "✉️" },
      variant: "email",
      placeholder: "tuo@email.it",
    },
    {
      id: "contact-phone",
      type: "text",
      key: "il_tuo_telefono",
      title: "Il tuo telefono",
      subtitle: "Per eventuali comunicazioni sulla prenotazione.",
      image: { kind: "emoji", value: "📞" },
      placeholder: "Es. 333 1234567",
    },
    {
      id: "review",
      type: "review",
      key: "controlla_la_prenotazione",
      title: "Controlla la prenotazione",
      subtitle: "Verifica i dati prima di confermare.",
    },
    {
      id: "confirmation",
      type: "confirmation",
      key: "prenotazione_confermata",
      title: "Prenotazione confermata!",
      message: "Ti aspettiamo. Riceverai un promemoria il giorno stesso.",
      primaryCta: "Torna alla home",
      secondaryCta: "Nuova prenotazione",
      resultActions: {
        pdfExport: { enabled: true, buttonLabel: "Scarica la prenotazione (PDF)" },
        nativeShare: { enabled: true, buttonLabel: "Condividi" },
      },
    },
  ],
})
