import { parseFlow, type Flow } from "@flowkit-io/core"

/** Preset for booking a restaurant table. */
export const restaurantFlow: Flow = parseFlow({
  id: "restaurant",
  title: "Prenota un tavolo",
  steps: [
    {
      id: "intro",
      type: "intro",
      title: "Prenota un tavolo",
      subtitle: "Scegli sede, data e numero di ospiti in meno di un minuto.",
      emoji: "🍽️",
      cta: "Prenota un tavolo →",
    },
    {
      id: "branch",
      type: "select-cards",
      title: "Quale sede?",
      icon: "📍",
      multiple: false,
      options: [
        { value: "centro", label: "Centro", emoji: "🏙️", description: "Via Roma, 12" },
        { value: "lungomare", label: "Lungomare", emoji: "🌊", description: "Via del Porto, 4" },
        { value: "collina", label: "Collina", emoji: "🌳", description: "Via dei Colli, 88" },
      ],
    },
    {
      id: "party-size",
      type: "text",
      title: "In quanti sarete?",
      icon: "🧑‍🤝‍🧑",
      variant: "number",
      placeholder: "Es. 4",
    },
    {
      id: "date-time",
      type: "date-time",
      title: "Quando?",
      icon: "🗓️",
      mode: "datetime",
      disablePast: true,
    },
    {
      id: "seating",
      type: "chips",
      title: "Dove preferisci sederti?",
      icon: "🪑",
      multiple: false,
      options: [
        { value: "indoor", label: "Interno" },
        { value: "outdoor", label: "Esterno" },
        { value: "bar", label: "Bancone" },
      ],
    },
    {
      id: "occasion",
      type: "select-cards",
      title: "Un'occasione speciale?",
      icon: "🎉",
      required: false,
      multiple: false,
      options: [
        { value: "birthday", label: "Compleanno", emoji: "🎂" },
        { value: "anniversary", label: "Anniversario", emoji: "💐" },
        { value: "business", label: "Cena di lavoro", emoji: "💼" },
      ],
    },
    {
      id: "dietary-notes",
      type: "notes",
      title: "Allergie o richieste particolari?",
      subtitle: "Facoltativo.",
      icon: "📝",
      required: false,
      placeholder: "Es. intolleranza al glutine, seggiolone per bambini…",
    },
    {
      id: "contact-name",
      type: "text",
      title: "A che nome?",
      icon: "🧾",
      placeholder: "Nome e cognome",
    },
    {
      id: "contact-email",
      type: "text",
      title: "La tua email",
      icon: "✉️",
      variant: "email",
      placeholder: "tuo@email.it",
    },
    {
      id: "contact-phone",
      type: "text",
      title: "Il tuo telefono",
      icon: "📞",
      placeholder: "Es. 333 1234567",
    },
    {
      id: "review",
      type: "review",
      title: "Controlla la prenotazione",
      subtitle: "Verifica i dati prima di confermare.",
    },
    {
      id: "confirmation",
      type: "confirmation",
      title: "Prenotazione confermata!",
      message: "Ti aspettiamo. Riceverai un promemoria il giorno stesso.",
      primaryCta: "Torna alla home",
      secondaryCta: "Nuova prenotazione",
      resultActions: {
        pdfExport: { enabled: true, buttonLabel: "Scarica la prenotazione (PDF)" },
        nativeShare: { enabled: true, buttonLabel: "Condividi" },
      },
    },
  ],
})
